//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _CICWEBIntegration.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.15:4052/CICTEST/WS/CIC%20JIPANGE%20PENSION%20PLAN/Codeunit/CICIn" +
            "tegrations")]
        public string _CICWEBIntegration_IntegrationCodeunit_CICIntegrations {
            get {
                return ((string)(this["_CICWEBIntegration_IntegrationCodeunit_CICIntegrations"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://erptest.cicdom.local/MicrosoftDynamicsAXAif60/CICFPASVendorCreation/xppser" +
            "vice.svc")]
        public string _CICWEBIntegration_ERPFPASTEst_RoutingService {
            get {
                return ((string)(this["_CICWEBIntegration_ERPFPASTEst_RoutingService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7777/Service.svc")]
        public string _CICWEBIntegration_DBSLServerFPas_Service1 {
            get {
                return ((string)(this["_CICWEBIntegration_DBSLServerFPas_Service1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://erptest.cicdom.local/MicrosoftDynamicsAXAif60/CICFPASCustomerCreation/xpps" +
            "ervice.svc")]
        public string _CICWEBIntegration_fPASAXCustomerService_RoutingService {
            get {
                return ((string)(this["_CICWEBIntegration_fPASAXCustomerService_RoutingService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://erptest.cicdom.local/MicrosoftDynamicsAXAif60/CICFPASAPInvoiceJournal/xpps" +
            "ervice.svc")]
        public string _CICWEBIntegration_fPASAXInvoiceJournalService_RoutingService {
            get {
                return ((string)(this["_CICWEBIntegration_fPASAXInvoiceJournalService_RoutingService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://erptest.cicdom.local/MicrosoftDynamicsAXAif60/CICFPASAPPaymentJournal/xpps" +
            "ervice.svc")]
        public string _CICWEBIntegration_fPASAXPaymentJournalService_RoutingService {
            get {
                return ((string)(this["_CICWEBIntegration_fPASAXPaymentJournalService_RoutingService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://erptest.cicdom.local/MicrosoftDynamicsAXAif60/CICFPASARPaymentJournal/xpps" +
            "ervice.svc")]
        public string _CICWEBIntegration_fPASAXARPaymentJournalService_RoutingService {
            get {
                return ((string)(this["_CICWEBIntegration_fPASAXARPaymentJournalService_RoutingService"]));
            }
        }
    }
}
